// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod carapace {
    pub mod plugin {
        /// Host-provided capabilities for plugins
        /// SECURITY: All functions enforce plugin isolation and resource limits
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod host {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Media fetch (with SSRF protection)
            /// SECURITY: Blocks private IPs, localhost, metadata endpoints
            #[derive(Clone)]
            pub struct MediaFetchResult {
                pub ok: bool,
                pub local_path: Option<_rt::String>,
                /// Temporary path, valid for 1 hour
                pub mime_type: Option<_rt::String>,
                pub size: Option<u64>,
                pub error: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for MediaFetchResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("MediaFetchResult")
                        .field("ok", &self.ok)
                        .field("local-path", &self.local_path)
                        .field("mime-type", &self.mime_type)
                        .field("size", &self.size)
                        .field("error", &self.error)
                        .finish()
                }
            }
            /// HTTP client (outbound requests)
            /// SECURITY: Same SSRF protections as media-fetch
            /// SECURITY: Rate limited to 100 requests/minute per plugin
            #[derive(Clone)]
            pub struct HttpRequest {
                pub method: _rt::String,
                /// GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS
                pub url: _rt::String,
                /// Must be http/https, max 2048 chars
                pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                /// Host header set by host
                pub body: Option<_rt::Vec<u8>>,
            }
            impl ::core::fmt::Debug for HttpRequest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("HttpRequest")
                        .field("method", &self.method)
                        .field("url", &self.url)
                        .field("headers", &self.headers)
                        .field("body", &self.body)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct HttpResponse {
                pub status: u16,
                pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                pub body: Option<_rt::Vec<u8>>,
            }
            impl ::core::fmt::Debug for HttpResponse {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("HttpResponse")
                        .field("status", &self.status)
                        .field("headers", &self.headers)
                        .field("body", &self.body)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Logging - rate limited to 1000 messages/minute
            pub fn log_debug(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-debug"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Max 4KB per message
            pub fn log_info(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-info"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn log_warn(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-warn"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn log_error(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-error"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Configuration - scoped to plugins.<plugin-id>.*
            /// SECURITY: Cannot read gateway-level config
            pub fn config_get(key: &str) -> Option<_rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "config-get"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Credentials (secure storage)
            /// SECURITY: Keys automatically prefixed with plugin ID
            /// Plugin calls credential-get("token") -> host reads "<plugin-id>:token"
            pub fn credential_get(key: &str) -> Option<_rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "credential-get"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn credential_set(key: &str, value: &str) -> bool {
                unsafe {
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = value;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "credential-set"]
                        fn wit_import2(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                        ) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                    ) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe {
                        wit_import2(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1)
                    };
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn media_fetch(
                url: &str,
                max_bytes: Option<u64>,
                timeout_ms: Option<u32>,
            ) -> MediaFetchResult {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 32 + 8 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 32
                            + 8 * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = url;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let (result1_0, result1_1) = match max_bytes {
                        Some(e) => (1i32, _rt::as_i64(e)),
                        None => (0i32, 0i64),
                    };
                    let (result2_0, result2_1) = match timeout_ms {
                        Some(e) => (1i32, _rt::as_i32(e)),
                        None => (0i32, 0i32),
                    };
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "media-fetch"]
                        fn wit_import4(
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: i64,
                            _: i32,
                            _: i32,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import4(
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: i64,
                        _: i32,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import4(
                            ptr0.cast_mut(),
                            len0,
                            result1_0,
                            result1_1,
                            result2_0,
                            result2_1,
                            ptr3,
                        )
                    };
                    let l5 = i32::from(*ptr3.add(0).cast::<u8>());
                    let l6 = i32::from(
                        *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l10 = i32::from(
                        *ptr3.add(4 * ::core::mem::size_of::<*const u8>()).cast::<u8>(),
                    );
                    let l14 = i32::from(
                        *ptr3
                            .add(8 + 6 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let l16 = i32::from(
                        *ptr3
                            .add(24 + 6 * ::core::mem::size_of::<*const u8>())
                            .cast::<u8>(),
                    );
                    let result20 = MediaFetchResult {
                        ok: _rt::bool_lift(l5 as u8),
                        local_path: match l6 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l7 = *ptr3
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *ptr3
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len9 = l8;
                                    let bytes9 = _rt::Vec::from_raw_parts(
                                        l7.cast(),
                                        len9,
                                        len9,
                                    );
                                    _rt::string_lift(bytes9)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        mime_type: match l10 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l11 = *ptr3
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l12 = *ptr3
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len13 = l12;
                                    let bytes13 = _rt::Vec::from_raw_parts(
                                        l11.cast(),
                                        len13,
                                        len13,
                                    );
                                    _rt::string_lift(bytes13)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        size: match l14 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l15 = *ptr3
                                        .add(16 + 6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<i64>();
                                    l15 as u64
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        error: match l16 {
                            0 => None,
                            1 => {
                                let e = {
                                    let l17 = *ptr3
                                        .add(24 + 7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l18 = *ptr3
                                        .add(24 + 8 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let len19 = l18;
                                    let bytes19 = _rt::Vec::from_raw_parts(
                                        l17.cast(),
                                        len19,
                                        len19,
                                    );
                                    _rt::string_lift(bytes19)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    };
                    result20
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn http_fetch(req: &HttpRequest) -> Result<HttpResponse, _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 7 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 7
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let HttpRequest {
                        method: method0,
                        url: url0,
                        headers: headers0,
                        body: body0,
                    } = req;
                    let vec1 = method0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = url0;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let vec6 = headers0;
                    let len6 = vec6.len();
                    let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec6.len() * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result6 = if layout6.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout6);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec6.into_iter().enumerate() {
                        let base = result6
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        {
                            let (t3_0, t3_1) = e;
                            let vec4 = t3_0;
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = t3_1;
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    }
                    let (result8_0, result8_1, result8_2) = match body0 {
                        Some(e) => {
                            let vec7 = e;
                            let ptr7 = vec7.as_ptr().cast::<u8>();
                            let len7 = vec7.len();
                            (1i32, ptr7.cast_mut(), len7)
                        }
                        None => (0i32, ::core::ptr::null_mut(), 0usize),
                    };
                    let ptr9 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "carapace:plugin/host@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "http-fetch"]
                        fn wit_import10(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import10(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import10(
                            ptr1.cast_mut(),
                            len1,
                            ptr2.cast_mut(),
                            len2,
                            result6,
                            len6,
                            result8_0,
                            result8_1,
                            result8_2,
                            ptr9,
                        )
                    };
                    let l11 = i32::from(*ptr9.add(0).cast::<u8>());
                    let result29 = match l11 {
                        0 => {
                            let e = {
                                let l12 = i32::from(
                                    *ptr9.add(::core::mem::size_of::<*const u8>()).cast::<u16>(),
                                );
                                let l13 = *ptr9
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l14 = *ptr9
                                    .add(3 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let base21 = l13;
                                let len21 = l14;
                                let mut result21 = _rt::Vec::with_capacity(len21);
                                for i in 0..len21 {
                                    let base = base21
                                        .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                    let e21 = {
                                        let l15 = *base.add(0).cast::<*mut u8>();
                                        let l16 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len17 = l16;
                                        let bytes17 = _rt::Vec::from_raw_parts(
                                            l15.cast(),
                                            len17,
                                            len17,
                                        );
                                        let l18 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l19 = *base
                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len20 = l19;
                                        let bytes20 = _rt::Vec::from_raw_parts(
                                            l18.cast(),
                                            len20,
                                            len20,
                                        );
                                        (_rt::string_lift(bytes17), _rt::string_lift(bytes20))
                                    };
                                    result21.push(e21);
                                }
                                _rt::cabi_dealloc(
                                    base21,
                                    len21 * (4 * ::core::mem::size_of::<*const u8>()),
                                    ::core::mem::size_of::<*const u8>(),
                                );
                                let l22 = i32::from(
                                    *ptr9
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>(),
                                );
                                HttpResponse {
                                    status: l12 as u16,
                                    headers: result21,
                                    body: match l22 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l23 = *ptr9
                                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<*mut u8>();
                                                let l24 = *ptr9
                                                    .add(6 * ::core::mem::size_of::<*const u8>())
                                                    .cast::<usize>();
                                                let len25 = l24;
                                                _rt::Vec::from_raw_parts(l23.cast(), len25, len25)
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    },
                                }
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l26 = *ptr9
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l27 = *ptr9
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len28 = l27;
                                let bytes28 = _rt::Vec::from_raw_parts(
                                    l26.cast(),
                                    len28,
                                    len28,
                                );
                                _rt::string_lift(bytes28)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    if layout6.size() != 0 {
                        _rt::alloc::dealloc(result6.cast(), layout6);
                    }
                    result29
                }
            }
        }
        /// Core types shared across all capabilities
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Result type for operations that can fail
            #[derive(Clone)]
            pub struct PluginError {
                pub code: _rt::String,
                pub message: _rt::String,
                pub retryable: bool,
            }
            impl ::core::fmt::Debug for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginError")
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .field("retryable", &self.retryable)
                        .finish()
                }
            }
            impl ::core::fmt::Display for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for PluginError {}
            /// Message delivery result
            #[derive(Clone)]
            pub struct DeliveryResult {
                pub ok: bool,
                pub message_id: Option<_rt::String>,
                pub error: Option<_rt::String>,
                /// v1 compatibility: retryable is boolean-only. Native channels can
                /// surface Retry-After metadata; WASM providers need a future WIT
                /// version before they can return retry-after-ms.
                pub retryable: bool,
            }
            impl ::core::fmt::Debug for DeliveryResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("DeliveryResult")
                        .field("ok", &self.ok)
                        .field("message-id", &self.message_id)
                        .field("error", &self.error)
                        .field("retryable", &self.retryable)
                        .finish()
                }
            }
            /// Chat types supported by channels
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum ChatType {
                Dm,
                Group,
                Channel,
                Thread,
            }
            impl ::core::fmt::Debug for ChatType {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ChatType::Dm => f.debug_tuple("ChatType::Dm").finish(),
                        ChatType::Group => f.debug_tuple("ChatType::Group").finish(),
                        ChatType::Channel => f.debug_tuple("ChatType::Channel").finish(),
                        ChatType::Thread => f.debug_tuple("ChatType::Thread").finish(),
                    }
                }
            }
            impl ChatType {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> ChatType {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => ChatType::Dm,
                        1 => ChatType::Group,
                        2 => ChatType::Channel,
                        3 => ChatType::Thread,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Outbound message context
            #[derive(Clone)]
            pub struct OutboundContext {
                pub to: _rt::String,
                /// Recipient identifier
                pub text: _rt::String,
                /// Max 64KB
                pub media_url: Option<_rt::String>,
                /// Validated by host (SSRF protection)
                pub gif_playback: bool,
                pub reply_to_id: Option<_rt::String>,
                pub thread_id: Option<_rt::String>,
                pub account_id: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for OutboundContext {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("OutboundContext")
                        .field("to", &self.to)
                        .field("text", &self.text)
                        .field("media-url", &self.media_url)
                        .field("gif-playback", &self.gif_playback)
                        .field("reply-to-id", &self.reply_to_id)
                        .field("thread-id", &self.thread_id)
                        .field("account-id", &self.account_id)
                        .finish()
                }
            }
            /// Poll input
            #[derive(Clone)]
            pub struct PollInput {
                pub question: _rt::String,
                /// Max 300 chars
                pub options: _rt::Vec<_rt::String>,
                /// 2-12 options, each max 100 chars
                pub allow_multiple: bool,
            }
            impl ::core::fmt::Debug for PollInput {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PollInput")
                        .field("question", &self.question)
                        .field("options", &self.options)
                        .field("allow-multiple", &self.allow_multiple)
                        .finish()
                }
            }
            /// Poll context for sending
            #[derive(Clone)]
            pub struct PollContext {
                pub to: _rt::String,
                pub poll: PollInput,
                pub account_id: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for PollContext {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PollContext")
                        .field("to", &self.to)
                        .field("poll", &self.poll)
                        .field("account-id", &self.account_id)
                        .finish()
                }
            }
            /// Tool invocation context
            /// SECURITY: sandboxed flag indicates restricted execution environment
            #[derive(Clone)]
            pub struct ToolContext {
                pub agent_id: Option<_rt::String>,
                pub session_key: Option<_rt::String>,
                pub message_channel: Option<_rt::String>,
                pub sandboxed: bool,
            }
            impl ::core::fmt::Debug for ToolContext {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ToolContext")
                        .field("agent-id", &self.agent_id)
                        .field("session-key", &self.session_key)
                        .field("message-channel", &self.message_channel)
                        .field("sandboxed", &self.sandboxed)
                        .finish()
                }
            }
            /// Tool result
            #[derive(Clone)]
            pub struct ToolResult {
                pub success: bool,
                pub result: Option<_rt::String>,
                /// Max 1MB
                pub error: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for ToolResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ToolResult")
                        .field("success", &self.success)
                        .field("result", &self.result)
                        .field("error", &self.error)
                        .finish()
                }
            }
            /// Hook event
            #[derive(Clone)]
            pub struct HookEvent {
                pub hook_name: _rt::String,
                pub payload: _rt::String,
            }
            impl ::core::fmt::Debug for HookEvent {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("HookEvent")
                        .field("hook-name", &self.hook_name)
                        .field("payload", &self.payload)
                        .finish()
                }
            }
            /// Hook result
            /// SECURITY: modified-payload only honored for modifiable hooks
            #[derive(Clone)]
            pub struct HookResult {
                pub handled: bool,
                pub cancel: bool,
                /// Only honored for cancellable hooks
                pub modified_payload: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for HookResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("HookResult")
                        .field("handled", &self.handled)
                        .field("cancel", &self.cancel)
                        .field("modified-payload", &self.modified_payload)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod carapace {
        pub mod plugin {
            /// Plugin manifest
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod manifest {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// Plugin kinds
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum PluginKind {
                    Channel,
                    Tool,
                    Webhook,
                    Service,
                    Hook,
                }
                impl ::core::fmt::Debug for PluginKind {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            PluginKind::Channel => {
                                f.debug_tuple("PluginKind::Channel").finish()
                            }
                            PluginKind::Tool => {
                                f.debug_tuple("PluginKind::Tool").finish()
                            }
                            PluginKind::Webhook => {
                                f.debug_tuple("PluginKind::Webhook").finish()
                            }
                            PluginKind::Service => {
                                f.debug_tuple("PluginKind::Service").finish()
                            }
                            PluginKind::Hook => {
                                f.debug_tuple("PluginKind::Hook").finish()
                            }
                        }
                    }
                }
                impl PluginKind {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> PluginKind {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => PluginKind::Channel,
                            1 => PluginKind::Tool,
                            2 => PluginKind::Webhook,
                            3 => PluginKind::Service,
                            4 => PluginKind::Hook,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                /// Plugin manifest
                #[derive(Clone)]
                pub struct PluginManifest {
                    pub id: _rt::String,
                    /// Lowercase alphanumeric + hyphens, max 32 chars
                    pub name: _rt::String,
                    /// Display name, max 64 chars
                    pub description: _rt::String,
                    /// Max 500 chars
                    pub version: _rt::String,
                    /// Semver format
                    pub kind: PluginKind,
                }
                impl ::core::fmt::Debug for PluginManifest {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("PluginManifest")
                            .field("id", &self.id)
                            .field("name", &self.name)
                            .field("description", &self.description)
                            .field("version", &self.version)
                            .field("kind", &self.kind)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_manifest_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_manifest();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let PluginManifest {
                        id: id2,
                        name: name2,
                        description: description2,
                        version: version2,
                        kind: kind2,
                    } = result0;
                    let vec3 = (id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (name2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = (description2.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (version2.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr1.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    *ptr1.add(8 * ::core::mem::size_of::<*const u8>()).cast::<u8>() = (kind2
                        .clone() as i32) as u8;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_manifest<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                    let l6 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l6, l7, 1);
                }
                pub trait Guest {
                    /// Get plugin manifest
                    fn get_manifest() -> PluginManifest;
                }
                #[doc(hidden)]
                macro_rules! __export_carapace_plugin_manifest_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "carapace:plugin/manifest@1.0.0#get-manifest")] unsafe extern "C"
                        fn export_get_manifest() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_manifest_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_carapace:plugin/manifest@1.0.0#get-manifest")] unsafe
                        extern "C" fn _post_return_get_manifest(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_get_manifest::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_carapace_plugin_manifest_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 9 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 9
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Tool definition and execution
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod tool {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ToolContext = super::super::super::super::carapace::plugin::types::ToolContext;
                pub type ToolResult = super::super::super::super::carapace::plugin::types::ToolResult;
                pub type PluginError = super::super::super::super::carapace::plugin::types::PluginError;
                /// Tool metadata
                #[derive(Clone)]
                pub struct ToolDefinition {
                    pub name: _rt::String,
                    /// Lowercase alphanumeric + underscores, max 64 chars
                    pub description: _rt::String,
                    /// Max 1024 chars
                    pub input_schema: _rt::String,
                }
                impl ::core::fmt::Debug for ToolDefinition {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ToolDefinition")
                            .field("name", &self.name)
                            .field("description", &self.description)
                            .field("input-schema", &self.input_schema)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_get_definitions_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::get_definitions();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec6 = result0;
                    let len6 = vec6.len();
                    let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec6.len() * (6 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result6 = if layout6.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout6);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec6.into_iter().enumerate() {
                        let base = result6
                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                        {
                            let ToolDefinition {
                                name: name2,
                                description: description2,
                                input_schema: input_schema2,
                            } = e;
                            let vec3 = (name2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (description2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (input_schema2.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1.add(0).cast::<*mut u8>() = result6;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_get_definitions<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base8 = l0;
                    let len8 = l1;
                    for i in 0..len8 {
                        let base = base8
                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l5 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                            let l6 = *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l7 = *base
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base8,
                        len8 * (6 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_invoke_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: i32,
                    arg8: *mut u8,
                    arg9: usize,
                    arg10: i32,
                    arg11: *mut u8,
                    arg12: usize,
                    arg13: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let result5 = T::invoke(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        super::super::super::super::carapace::plugin::types::ToolContext {
                            agent_id: match arg4 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len2 = arg6;
                                        let bytes2 = _rt::Vec::from_raw_parts(
                                            arg5.cast(),
                                            len2,
                                            len2,
                                        );
                                        _rt::string_lift(bytes2)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            session_key: match arg7 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len3 = arg9;
                                        let bytes3 = _rt::Vec::from_raw_parts(
                                            arg8.cast(),
                                            len3,
                                            len3,
                                        );
                                        _rt::string_lift(bytes3)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            message_channel: match arg10 {
                                0 => None,
                                1 => {
                                    let e = {
                                        let len4 = arg12;
                                        let bytes4 = _rt::Vec::from_raw_parts(
                                            arg11.cast(),
                                            len4,
                                            len4,
                                        );
                                        _rt::string_lift(bytes4)
                                    };
                                    Some(e)
                                }
                                _ => _rt::invalid_enum_discriminant(),
                            },
                            sandboxed: _rt::bool_lift(arg13 as u8),
                        },
                    );
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result5 {
                        Ok(e) => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::carapace::plugin::types::ToolResult {
                                success: success7,
                                result: result7,
                                error: error7,
                            } = e;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match success7 {
                                true => 1,
                                false => 0,
                            }) as u8;
                            match result7 {
                                Some(e) => {
                                    *ptr6
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *ptr6
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len8;
                                    *ptr6
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                }
                                None => {
                                    *ptr6
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                            match error7 {
                                Some(e) => {
                                    *ptr6
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec9 = (e.into_bytes()).into_boxed_slice();
                                    let ptr9 = vec9.as_ptr().cast::<u8>();
                                    let len9 = vec9.len();
                                    ::core::mem::forget(vec9);
                                    *ptr6
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len9;
                                    *ptr6
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr9.cast_mut();
                                }
                                None => {
                                    *ptr6
                                        .add(5 * ::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                }
                            };
                        }
                        Err(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::carapace::plugin::types::PluginError {
                                code: code10,
                                message: message10,
                                retryable: retryable10,
                            } = e;
                            let vec11 = (code10.into_bytes()).into_boxed_slice();
                            let ptr11 = vec11.as_ptr().cast::<u8>();
                            let len11 = vec11.len();
                            ::core::mem::forget(vec11);
                            *ptr6
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len11;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr11.cast_mut();
                            let vec12 = (message10.into_bytes()).into_boxed_slice();
                            let ptr12 = vec12.as_ptr().cast::<u8>();
                            let len12 = vec12.len();
                            ::core::mem::forget(vec12);
                            *ptr6
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len12;
                            *ptr6
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr12.cast_mut();
                            *ptr6
                                .add(5 * ::core::mem::size_of::<*const u8>())
                                .cast::<u8>() = (match retryable10 {
                                true => 1,
                                false => 0,
                            }) as u8;
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_invoke<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = i32::from(
                                *arg0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l1 {
                                0 => {}
                                _ => {
                                    let l2 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(4 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                            }
                            let l4 = i32::from(
                                *arg0
                                    .add(5 * ::core::mem::size_of::<*const u8>())
                                    .cast::<u8>(),
                            );
                            match l4 {
                                0 => {}
                                _ => {
                                    let l5 = *arg0
                                        .add(6 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(7 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                            }
                        }
                        _ => {
                            let l7 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l8 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l7, l8, 1);
                            let l9 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l10 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l9, l10, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Get tool definitions provided by this plugin
                    fn get_definitions() -> _rt::Vec<ToolDefinition>;
                    /// Invoke a tool
                    /// SECURITY: ctx.sandboxed indicates restricted environment
                    fn invoke(
                        name: _rt::String,
                        params: _rt::String,
                        ctx: ToolContext,
                    ) -> Result<ToolResult, PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_carapace_plugin_tool_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "carapace:plugin/tool@1.0.0#get-definitions")] unsafe extern "C"
                        fn export_get_definitions() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_get_definitions_cabi::<$ty > () } }
                        #[unsafe (export_name =
                        "cabi_post_carapace:plugin/tool@1.0.0#get-definitions")] unsafe
                        extern "C" fn _post_return_get_definitions(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_get_definitions::<$ty
                        > (arg0) } } #[unsafe (export_name =
                        "carapace:plugin/tool@1.0.0#invoke")] unsafe extern "C" fn
                        export_invoke(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
                        arg3 : usize, arg4 : i32, arg5 : * mut u8, arg6 : usize, arg7 :
                        i32, arg8 : * mut u8, arg9 : usize, arg10 : i32, arg11 : * mut
                        u8, arg12 : usize, arg13 : i32,) -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_invoke_cabi::<$ty > (arg0, arg1,
                        arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11,
                        arg12, arg13) } } #[unsafe (export_name =
                        "cabi_post_carapace:plugin/tool@1.0.0#invoke")] unsafe extern "C"
                        fn _post_return_invoke(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_invoke::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_carapace_plugin_tool_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 8 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_tool_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::carapace::plugin::manifest::__export_carapace_plugin_manifest_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::carapace::plugin::manifest);
        $($path_to_types_root)*::
        exports::carapace::plugin::tool::__export_carapace_plugin_tool_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::carapace::plugin::tool);
    };
}
#[doc(inline)]
pub(crate) use __export_tool_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:carapace:plugin@1.0.0:tool-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1876] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd2\x0d\x01A\x02\x01\
A\x0b\x01B\x1c\x01ks\x01kw\x01r\x05\x02ok\x7f\x0alocal-path\0\x09mime-type\0\x04\
size\x01\x05error\0\x04\0\x12media-fetch-result\x03\0\x02\x01o\x02ss\x01p\x04\x01\
p}\x01k\x06\x01r\x04\x06methods\x03urls\x07headers\x05\x04body\x07\x04\0\x0chttp\
-request\x03\0\x08\x01r\x03\x06status{\x07headers\x05\x04body\x07\x04\0\x0dhttp-\
response\x03\0\x0a\x01@\x01\x07messages\x01\0\x04\0\x09log-debug\x01\x0c\x04\0\x08\
log-info\x01\x0c\x04\0\x08log-warn\x01\x0c\x04\0\x09log-error\x01\x0c\x01@\x01\x03\
keys\0\0\x04\0\x0aconfig-get\x01\x0d\x04\0\x0ecredential-get\x01\x0d\x01@\x02\x03\
keys\x05values\0\x7f\x04\0\x0ecredential-set\x01\x0e\x01ky\x01@\x03\x03urls\x09m\
ax-bytes\x01\x0atimeout-ms\x0f\0\x03\x04\0\x0bmedia-fetch\x01\x10\x01j\x01\x0b\x01\
s\x01@\x01\x03req\x09\0\x11\x04\0\x0ahttp-fetch\x01\x12\x03\0\x1acarapace:plugin\
/host@1.0.0\x05\0\x01B\x1c\x01r\x03\x04codes\x07messages\x09retryable\x7f\x04\0\x0c\
plugin-error\x03\0\0\x01ks\x01r\x04\x02ok\x7f\x0amessage-id\x02\x05error\x02\x09\
retryable\x7f\x04\0\x0fdelivery-result\x03\0\x03\x01kw\x01r\x04\x03urls\x09mime-\
type\x02\x08filename\x02\x04size\x05\x04\0\x10media-attachment\x03\0\x06\x01m\x04\
\x02dm\x05group\x07channel\x06thread\x04\0\x09chat-type\x03\0\x08\x01k\x07\x01r\x0c\
\x0achannel-ids\x0aaccount-id\x02\x04froms\x0bsender-name\x02\x04texts\x05media\x0a\
\x0breply-to-id\x02\x09thread-id\x02\x09timestampw\x09chat-type\x09\x08group-id\x02\
\x0agroup-name\x02\x04\0\x0finbound-message\x03\0\x0b\x01r\x07\x02tos\x04texts\x09\
media-url\x02\x0cgif-playback\x7f\x0breply-to-id\x02\x09thread-id\x02\x0aaccount\
-id\x02\x04\0\x10outbound-context\x03\0\x0d\x01ps\x01r\x03\x08questions\x07optio\
ns\x0f\x0eallow-multiple\x7f\x04\0\x0apoll-input\x03\0\x10\x01r\x03\x02tos\x04po\
ll\x11\x0aaccount-id\x02\x04\0\x0cpoll-context\x03\0\x12\x01r\x04\x08agent-id\x02\
\x0bsession-key\x02\x0fmessage-channel\x02\x09sandboxed\x7f\x04\0\x0ctool-contex\
t\x03\0\x14\x01r\x03\x07success\x7f\x06result\x02\x05error\x02\x04\0\x0btool-res\
ult\x03\0\x16\x01r\x02\x09hook-names\x07payloads\x04\0\x0ahook-event\x03\0\x18\x01\
r\x03\x07handled\x7f\x06cancel\x7f\x10modified-payload\x02\x04\0\x0bhook-result\x03\
\0\x1a\x03\0\x1bcarapace:plugin/types@1.0.0\x05\x01\x01B\x06\x01m\x05\x07channel\
\x04tool\x07webhook\x07service\x04hook\x04\0\x0bplugin-kind\x03\0\0\x01r\x05\x02\
ids\x04names\x0bdescriptions\x07versions\x04kind\x01\x04\0\x0fplugin-manifest\x03\
\0\x02\x01@\0\0\x03\x04\0\x0cget-manifest\x01\x04\x04\0\x1ecarapace:plugin/manif\
est@1.0.0\x05\x02\x02\x03\0\x01\x0ctool-context\x02\x03\0\x01\x0btool-result\x02\
\x03\0\x01\x0cplugin-error\x01B\x0e\x02\x03\x02\x01\x03\x04\0\x0ctool-context\x03\
\0\0\x02\x03\x02\x01\x04\x04\0\x0btool-result\x03\0\x02\x02\x03\x02\x01\x05\x04\0\
\x0cplugin-error\x03\0\x04\x01r\x03\x04names\x0bdescriptions\x0cinput-schemas\x04\
\0\x0ftool-definition\x03\0\x06\x01p\x07\x01@\0\0\x08\x04\0\x0fget-definitions\x01\
\x09\x01j\x01\x03\x01\x05\x01@\x03\x04names\x06paramss\x03ctx\x01\0\x0a\x04\0\x06\
invoke\x01\x0b\x04\0\x1acarapace:plugin/tool@1.0.0\x05\x06\x04\0!carapace:plugin\
/tool-plugin@1.0.0\x04\0\x0b\x11\x01\0\x0btool-plugin\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
